language: ruby
rvm: 
  - 2.5.3
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
before_script:
  - cp config/database.yml.travis config/database.yml
services:
  - postgresql
script:
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
  - RAILS_ENV=test rails assets:precompile
  - RAILS_ENV=test bundle exec rspec
