# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'artworkdraft-web:$(build.buildId)'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5.3'
    addToPath: true
- script: apt-get install -y libpq-dev postgresql-10 build-essential
  displayName: "install postgres"
- script: gem install bundler
  displayName: "Install bundler"
- script: bundle install
  displayName: "Install gems"
- script: |
    RAILS_ENV=test rails db:setup
    RAILS_ENV=test rails db:migrate
    RAILS_ENV=test bundle exec rspec
  displayName: "Run Rspec"
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'