# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'artworkdraft-web:$(build.buildId)'

steps:
- script: |
    sudo apt-get install libgdbm-dev libncurses5-dev automake libtool bison libffi-dev
    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    curl -sSL https://get.rvm.io | bash -s stable
    source ~/.rvm/scripts/rvm
    rvm install 2.5.3
    rvm use 2.5.3 --default
  displayName: "Install Ruby 2.5.3"
- script: apt-get install -y libpq-dev postgresql-10 build-essential
  displayName: "install postgres"
- script: gem install bundler
  displayName: "Install bundler"
- script: bundle install
  displayName: "Install gems"
- script: |
    RAILS_ENV=test rails db:setup
    RAILS_ENV=test rails db:migrate
    RAILS_ENV=test bundle exec rspec
  displayName: "Run Rspec"
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
